image:
  repository: selcdacr.azurecr.io/selfcaremsexternalinterceptor

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.dev.selfcare.pagopa.it"
  MS_EXTERNAL_INTERCEPTOR_LOG_LEVEL: "DEBUG"
  SAP_EXCLUDED_INSTITUTION_TYPES: "SA"
  PRODUCTS_TO_RESEND: "prod-io,prod-io-sign,prod-interop,prod-pn"
