replicaCount: 0

image:
  repository: selcuacr.azurecr.io/selfcaremsexternalinterceptor
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.uat.selfcare.pagopa.it
      secretName: selc-internal-uat-selfcare-pagopa-it
  hosts:
    - host: selc.internal.uat.selfcare.pagopa.it
      paths:
        - path: /ms-external-interceptor/v1/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 300m
    memory: 500M
  limits:
    cpu: 500m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.uat.selfcare.pagopa.it"
  MS_EXTERNAL_INTERCEPTOR_LOG_LEVEL: "DEBUG"
  SAP_ALLOWED_INSTITUTION_TYPES: "PA,GSP,SA,AS,SCP"
  SAP_ALLOWED_ORIGIN: "IPA,SELC"
  PRODUCTS_TO_RESEND: "prod-pn,prod-io-sign,prod-io-premium"
  BYPASS_CHECK_ORGANIZATION: "false"
