image:
  repository: selcpacr.azurecr.io/selfcaremsexternalinterceptor
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.selfcare.pagopa.it"
  MS_EXTERNAL_INTERCEPTOR_LOG_LEVEL: "INFO"
  SAP_ALLOWED_INSTITUTION_TYPES: "PA"
  PRODUCTS_TO_RESEND: "prod-pn,prod-io-sign,prod-io-premium"
