image:
  repository: selcdacr.azurecr.io/selfcaremsexternalinterceptor

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /ms-external-interceptor/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: false

configEnvSpecific:
  INTERNAL_API_SERVICE_URL: "https://api.dev.selfcare.pagopa.it"
  MS_EXTERNAL_INTERCEPTOR_LOG_LEVEL: "DEBUG"
  SAP_ALLOWED_INSTITUTION_TYPES: "PA,GSP,SA,SA,SCP"
  SAP_ALLOWED_ORIGIN: "IPA,SELC"
  PRODUCTS_TO_RESEND: "prod-pn,prod-io-sign,prod-io-premium"
